---
version: "3.7"

services:
  s1aptester:
    volumes:
      - ${CONFIGS_DEFAULT_VOLUME}:/etc/magma
    image: ${DOCKER_REGISTRY}agw_s1aptester:${IMAGE_VERSION}
    container_name: s1aptester
    command: /bin/bash
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host

  trfgen:
    image: ${DOCKER_REGISTRY}agw_trfgen:${IMAGE_VERSION}
    container_name: trfgen
    privileged: true
    network_mode: host
