---
################################################################################
# Copyright 2022 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################
- name: Verify eth0 and eth1 exist
  assert:
    that:
      - "{{ ansible_facts['eth0'] is defined }}"
      - "{{ ansible_facts['eth1'] is defined }}"
    fail_msg: "eth0 and eth1 interfaces must exist"

- name: Get AGW deployment status
  stat:
    path: /var/opt/magma/docker/docker-compose.yaml
  register: agw_deployed

- name: Verify AGW is deployed
  assert:
    that: "{{ agw_deployed.stat.exists }}"
    fail_msg: "Deploy host as an AGW"

- name: Verify eth1 address
  assert:
    that: ansible_facts['eth1']['ipv4']['address']  == '192.168.60.142'
    fail_msg: "eth1 must have address 192.168.60.142"

- name: Verify eth0 address
  assert:
    that: ansible_facts['eth0']['ipv4']['address']  == '192.168.129.1'
    fail_msg: "eth0 must have address 192.168.129.1"

- name: Update ubuntu password
  user:
    name: ubuntu
    password: "{{ 'ubuntu' | password_hash('sha512', 'ubuntu') }}"

- name: Permit ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication|^#PasswordAuthentication'
    line: "PasswordAuthentication yes"
  register: password_auth

- name: Reload ssh
  systemd:
    name: ssh
    state: reloaded
  when: password_auth.changed

- name: Add docker registry to .env
  lineinfile:
    path: /var/opt/magma/docker/.env
    regexp: '^DOCKER_REGISTRY='
    line: "DOCKER_REGISTRY={{ docker_registry }}"
  when: docker_registry is defined

- name: "Build agw images"
  shell:
    cmd: "docker-compose build --parallel"
    chdir: /opt/magma/lte/gateway/docker
  when: docker_registry is not defined

- name: Insert ryu static service to pipelined
  lineinfile:
    path: /etc/magma/pipelined.yml
    search_string: "^static_services"
    insertafter: "^static_services"
    line: "  'ryu_rest_service',"

- name: "Start AGW containers"
  shell:
    cmd: "docker-compose --env-file .env -f docker-compose.yaml -f docker-compose.agw.s1ap.override.yaml up -d"
    chdir: /var/opt/magma/docker
