---
- name: Verify eth0 and eth1 exist
  assert:
    that:
      - "{{ ansible_facts['eth0'] is defined }}"
      - "{{ ansible_facts['eth1'] is defined }}"
    fail_msg: "eth0 and eth1 interfaces must exist"

- name: Get AGW containers status
  stat:
    path: /var/opt/magma/docker/docker-compose.yaml
  register: agw_deployed

- name: Verify AGW is deployed
  assert:
    that: "{{ agw_deployed.stat.exists }}"
    fail_msg: "Deploy host as an AGW"

- name: Verify eth1 address
  assert:
    that: ansible_facts['eth1']['ipv4']['address']  == '192.168.60.142'
    fail_msg: "eth1 must have address 192.168.60.142"

- name: Verify eth2 address
  assert:
    that: ansible_facts['eth2']['ipv4']['address']  == '192.168.129.1'
    fail_msg: "eth2 must have address 192.168.129.1"

- name: Update ubuntu password
  user:
    name: ubuntu
    password: "{{ 'ubuntu' | password_hash('sha512', 'ubuntu') }}"

- name: Permit ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication|^#PasswordAuthentication'
    line: "PasswordAuthentication yes"
  register: password_auth

- name: Reload ssh
  systemd:
    name: ssh
    state: reloaded
  when: password_auth.changed

- name: Add docker registry to .env
  lineinfile:
    path: /var/opt/magma/docker/.env
    regexp: '^DOCKER_REGISTRY='
    line: "DOCKER_REGISTRY={{ docker_registry }}"
  when: docker_registry is defined

- name: "Build agw images"
  shell:
    cmd: "docker-compose build --parallel"
    chdir: /opt/magma/lte/gateway/docker
  when: docker_registry is not defined

- name: "Start AGW containers"
  shell:
    cmd: "docker-compose --env-file .env -f docker-compose.yaml -f docker-compose.agw.s1ap.override.yaml up -d"
    chdir: /var/opt/magma/docker
