---
version: "3.7"

services:
  gateway_c:
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: lte/gateway/docker/services/c/Dockerfile

  gateway_python:
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: lte/gateway/docker/services/python/Dockerfile

  s1aptester:
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: lte/gateway/docker/services/s1aptester/Dockerfile

  trfgen:
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: lte/gateway/docker/services/trfgen/Dockerfile
